### ISSUE TITLE
Access to data at zero timestep

### ISSUE THREAD

**Issue by MrAdamStewart** [RICOHub01/QNG23-Challenge#6]
How will the interface work for the live simulation on Thursday, will we be using a downloaded dataset and the Drone_Sim class, as well as submit_answers function? or will there be some other method of retrieving data and submitting answers. 

In the current format for training we can access the full dataset while time_step is zero.

https://github.com/RICOHub01/QNG23-Challenge/blob/421be4b86a4ab88904e682d7ec7d92f4878f764c/qe_minesweeper.py#L185-L187

Cheers

**Comment by RDC-Mitchell** [comment]
Hi @MrAdamStewart 

That's a fair question, you will have a choice, you can either use:
1. a downloaded dataset similar to stage 1 & 2, this will give the full dataset with noise added, but our system will register you as having chosen to take the number of timesteps required to do a survey (10200). You are not required to use the Drone Simulator if this path is chosen.
2. a new drone simulator provided on Thursday, which instead of referring to a local dataset will refer to an online dataset- this will remove the `self.data` variable and ensure our online system will track your timesteps.

**Comment by MrAdamStewart** [comment]
@RDC-Mitchell, Ok makes sense ! Thank you for  that.

Cheers
